# Generated by Django 4.0.3 on 2022-03-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='group_name',
            new_name='Nombre de la organización/grupo',
        ),
    ]
