# Generated by Django 4.0.3 on 2022-03-26 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Categoria de propuestas',
                'verbose_name_plural': 'Categorias de propuestas',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Localidad de propuestas',
                'verbose_name_plural': 'Localidades de propuestas',
                'db_table': 'Localidad',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_charge', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('impact_sector', models.CharField(max_length=200, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(upload_to='pdf')),
                ('annex', models.FileField(upload_to='annex')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='base.category')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='base.locality')),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
                'db_table': 'Propuesta',
                'ordering': ('-created',),
            },
        ),
    ]
