# Generated by Django 4.0.3 on 2022-03-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(upload_to='pdf_convocatorias')),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'db_table': 'Inscripcion',
                'ordering': ('-created',),
            },
        ),
        migrations.AlterField(
            model_name='proposal',
            name='impact_sector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
