# Generated by Django 4.0.3 on 2022-03-26 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_inscriptions_alter_proposal_impact_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptions',
            name='begins',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscriptions',
            name='ends',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
