# Generated by Django 4.0.3 on 2022-03-26 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_inscriptions_begins_inscriptions_ends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ('-created', 'approved'), 'verbose_name': 'Propuesta', 'verbose_name_plural': 'Propuestas'},
        ),
        migrations.AddField(
            model_name='proposal',
            name='description',
            field=models.CharField(default='des', max_length=1000, verbose_name='Descripción de la problemática que se identificó'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='estimated_value',
            field=models.PositiveIntegerField(default=0, verbose_name='Descripción de la problemática que se identificó'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='justification',
            field=models.CharField(default='jus', max_length=1000, verbose_name='Descripción de la problemática que se identificó'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='objective',
            field=models.CharField(default='obj', max_length=200, verbose_name='Objetivo de la iniciativa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='problematic',
            field=models.CharField(default='proble', max_length=500, verbose_name='Descripción de la problemática que se identificó'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='annex',
            field=models.FileField(upload_to='annex', verbose_name='Adjunte aquí los anexos requeridos en un solo archivo'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='¿Aprobado?'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='base.category', verbose_name='Categoría en que incide'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='contact_charge',
            field=models.CharField(max_length=200, verbose_name='Cargo o posición de la persona de contacto'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='contact_name',
            field=models.CharField(max_length=200, verbose_name='Persona de contacto'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='contact_number',
            field=models.PositiveIntegerField(verbose_name='Número de contacto'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='group_name',
            field=models.CharField(max_length=200, verbose_name='Nombre de la organización/grupo'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='impact_sector',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Barrio o sector impactado por la propuesta'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='base.locality', verbose_name='Localidad de ubicación de la propuesta'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de la iniciativa'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pdf',
            field=models.FileField(upload_to='pdf', verbose_name='Adjunte aquí su propuesta en PDF'),
        ),
    ]
