# Generated by Django 4.0.3 on 2022-03-26 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_proposal_options_proposal_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Descripción')),
                ('number', models.PositiveIntegerField(verbose_name='Número de la fase')),
                ('pdf', models.FileField(upload_to='pdf_fases', verbose_name='Archivo PDF')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'db_table': 'Fase',
                'ordering': ('-number',),
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de la categoría'),
        ),
        migrations.AlterField(
            model_name='inscriptions',
            name='begins',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='inscriptions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='inscriptions',
            name='ends',
            field=models.DateField(verbose_name='Fecha final'),
        ),
        migrations.AlterField(
            model_name='inscriptions',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de la convocatoria'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de la localidad'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Descripción breve de la iniciativa'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='estimated_value',
            field=models.PositiveIntegerField(verbose_name='Indique el valor estimado de su iniciativa'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='justification',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Justificación de la iniciativa'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='objective',
            field=models.TextField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Objetivo de la iniciativa'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='problematic',
            field=models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Descripción de la problemática que se identificó'),
        ),
        migrations.AlterModelTable(
            name='inscriptions',
            table='Convocatoria',
        ),
    ]
