# Generated by Django 4.0.3 on 2022-03-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_phase_alter_category_name_alter_inscriptions_begins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='url_video',
            field=models.URLField(default='https://www.youtube.com/embed/6FVa8bJaf30', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='annex',
            field=models.FileField(upload_to='anexos_iniciativas', verbose_name='Adjunte aquí los anexos requeridos en un solo archivo'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pdf',
            field=models.FileField(upload_to='pdf_iniciativas', verbose_name='Adjunte aquí su propuesta en PDF'),
        ),
    ]
