# Generated by Django 4.0.3 on 2022-04-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_proposal_url_video_alter_proposal_annex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='terms_service',
            field=models.CharField(choices=[('S', 'Si')], default='Si', max_length=200, verbose_name='Acepta los términos de la política de tratamiento de datos personales'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='url_video',
            field=models.URLField(max_length=400, verbose_name='Pegue aquí la URL en Youtube con el video resumen de su propuesta'),
        ),
    ]
