# Generated by Django 4.0.3 on 2022-04-04 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_proposal_terms_service_alter_proposal_url_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='url_video',
            field=models.URLField(default='https://www.youtube.com/watch?v=ns82ksntYbY', max_length=400, verbose_name='URL en Youtube'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscriptions',
            name='pdf',
            field=models.FileField(upload_to='pdf_convocatorias', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='phase',
            name='pdf',
            field=models.FileField(upload_to='pdf_fases', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='annex',
            field=models.FileField(upload_to='anexos_iniciativas', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Adjunte aquí los anexos requeridos en un solo archivo'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pdf',
            field=models.FileField(upload_to='pdf_iniciativas', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Adjunte aquí su propuesta en PDF'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='terms_service',
            field=models.CharField(max_length=2, verbose_name='Acepta los términos de la política de tratamiento de datos personales'),
        ),
    ]
