# Generated by Django 4.0.3 on 2022-04-12 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_phase_url_video_alter_inscriptions_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la herramienta')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción de la herramienta')),
                ('pdf', models.FileField(upload_to='pdf_herramientas', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'db_table': 'Herramienta',
                'ordering': ('-name',),
            },
        ),
    ]
