# Generated by Django 4.0.3 on 2022-04-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_inscriptions_inscription_rename_tools_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('url_video', models.URLField(max_length=400, verbose_name='URL en Youtube con el video testimomio')),
            ],
        ),
    ]
