# Generated by Django 4.0.3 on 2022-04-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_testimony'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'ordering': ('-created',), 'verbose_name': 'Testimonio', 'verbose_name_plural': 'Testimonios'},
        ),
        migrations.AddField(
            model_name='testimony',
            name='name',
            field=models.CharField(default='none', max_length=100, verbose_name='Nombre de la herramienta'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='testimony',
            table='Testimonio',
        ),
    ]
