# Generated by Django 4.0.3 on 2022-04-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_testimony_options_testimony_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Imagen')),
                ('number', models.PositiveIntegerField(verbose_name='Número de la imagen')),
            ],
            options={
                'verbose_name': 'Carrusel',
                'verbose_name_plural': 'Carrusel',
                'db_table': 'Carrusel',
                'ordering': ('number',),
            },
        ),
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ('number',), 'verbose_name': 'Fase', 'verbose_name_plural': 'Fases'},
        ),
        migrations.AlterField(
            model_name='testimony',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
