# Generated by Django 4.0.3 on 2022-04-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_carousel_alter_phase_options_alter_testimony_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='images', verbose_name='Imagen')),
                ('number', models.PositiveIntegerField(verbose_name='Orden de la alianza')),
            ],
            options={
                'verbose_name': 'Alianza',
                'verbose_name_plural': 'Alianzas',
                'db_table': 'Alianza',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url', models.URLField(max_length=400, verbose_name='URL')),
                ('number', models.PositiveIntegerField(verbose_name='Orden de la red social')),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
                'db_table': 'SocialMedia',
                'ordering': ('number',),
            },
        ),
        migrations.AlterField(
            model_name='carousel',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Orden de la imagen'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Orden de la fase'),
        ),
    ]
