# Generated by Django 4.0.3 on 2022-04-15 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='data_agreement',
            field=models.TextField(default='ada', max_length=500, verbose_name='Autorización de tratamiento de datos personales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='form_intro',
            field=models.TextField(default='', max_length=500, verbose_name='Introducción de formulario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(default='', upload_to='images', verbose_name='Logo en menú'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='pdf_general',
            field=models.FileField(default='', upload_to='pdf_fases', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Unidad general'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='introduction',
            field=models.TextField(max_length=500, verbose_name='Texto introductorio'),
        ),
    ]
