# Generated by Django 4.0.3 on 2022-04-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_settings_data_agreement_settings_form_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='data_agreement',
            field=models.TextField(max_length=1000, verbose_name='Autorización de tratamiento de datos personales'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='form_intro',
            field=models.TextField(max_length=1000, verbose_name='Introducción de formulario'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='introduction',
            field=models.TextField(max_length=1000, verbose_name='Texto introductorio'),
        ),
    ]
