# Generated by Django 4.0.3 on 2022-04-29 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_settings_data_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='intro_image',
            field=models.ImageField(default='no', upload_to='images', verbose_name='Imagen introductoria (1920x1080)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscription',
            name='pdf',
            field=models.FileField(upload_to='pdf/convocatorias', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='phase',
            name='pdf',
            field=models.FileField(upload_to='pdf/fases', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='annex',
            field=models.FileField(upload_to='pdf/anexos_iniciativas', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Adjunte aquí los anexos requeridos en un solo archivo'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pdf',
            field=models.FileField(upload_to='pdf/iniciativas', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Adjunte aquí su propuesta en PDF'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='pdf',
            field=models.FileField(upload_to='pdf/herramientas', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
