# Generated by Django 4.0.3 on 2022-05-02 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_keyconcepts_delete_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('issue', models.CharField(max_length=100, verbose_name='Asunto')),
                ('message', models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Mensaje')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Enviado')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'Mensaje',
                'ordering': ('-created',),
            },
        ),
    ]
