# Generated by Django 4.0.3 on 2022-05-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_keyconcepts_description_alter_tool_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='contact_address',
            field=models.CharField(default='', max_length=100, verbose_name='Dirección contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='contact_phone',
            field=models.CharField(default='', max_length=100, verbose_name='Telefono contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='contact_text',
            field=models.TextField(default='', max_length=1000, verbose_name='Texto de contacto'),
            preserve_default=False,
        ),
    ]
