# Generated by Django 4.0.3 on 2022-05-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_settings_contact_address_settings_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='view',
            field=models.BooleanField(default=False, verbose_name='¿Visto?'),
        ),
    ]
