# Generated by Django 4.0.3 on 2022-05-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_contact_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='contact_address',
            field=models.TextField(max_length=100, verbose_name='Dirección contacto'),
        ),
    ]
