# Generated by Django 4.0.3 on 2022-05-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_settings_contact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='title_intro',
            field=models.CharField(default='', max_length=200, verbose_name='Título introductorio'),
            preserve_default=False,
        ),
    ]
